services:
 web:
  container_name: spring
  image: spring:0.2
  ports:
   - "8081:8081"
   - "8082:8082"
   - "8443:8443"
  depends_on:
   - "mysql8"
 mysql:
  container_name: mysql8
  image: mysql:8.0.26
  ports:
   - "3301:3306"
  volumes:
   - D:\opt\DockerVolumes\mysql\data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=kazi
   - MYSQL_USER=kazi
   - MYSQL_PASSWORD=kazi
   - MYSQL_DATABASE=test